// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
// import type { Metadata } from "next";
// import { Poppins, DM_Sans, Outfit } from "next/font/google";
// import "./globals.css";

// // Load fonts with proper configuration
// const poppins = Poppins({
//   variable: "--font-poppins",
//   subsets: ["latin"],
//   weight: ["600", "700", "800"],
//   display: 'swap',
// });

// const dmSans = DM_Sans({
//   variable: "--font-dm-sans", 
//   subsets: ["latin"],
//   weight: ["400", "500"],
//   display: 'swap',
// });

// const outfit = Outfit({
//   variable: "--font-outfit",
//   subsets: ["latin"],
//   weight: ["500", "700"],
//   display: 'swap',
// });

// export const metadata: Metadata = {
//   title: "Hey Humanz",
//   description: "Create. Display. Shine. - LED product sales, rentals, and ad creation collaborations",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" className={`${poppins.variable} ${dmSans.variable} ${outfit.variable}`}>
//       <body className="font-dm-sans antialiased">
//         {children}
//       </body>
//     </html>
//   );
// }


// import type { Metadata } from "next";
// import "./globals.css";
// import NextauthProvider from "./Provider";

// export const metadata: Metadata = {
//   title: "Hey Humanz",
//   description: "Create. Display. Shine. - LED product sales, rentals, and ad creation collaborations",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <head>
//         <link
//           href="https://fonts.googleapis.com/css2?family=Poppins:wght@600;700;800&family=DM+Sans:wght@400;500&family=Outfit:wght@500;700&display=swap"
//           rel="stylesheet"
//         />
//       </head>
//       <body className="font-dm-sans antialiased">   
//         <NextauthProvider>

//         {children}
//         </NextauthProvider>
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import "./globals.css";
import NextauthProvider from "./Provider";

export const metadata: Metadata = {
  title: "Hey Humanz",
  description: "Create. Display. Shine. - LED product sales, rentals, and ad creation collaborations",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@600;700;800&family=DM+Sans:wght@400;500&family=Outfit:wght@500;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="font-dm-sans antialiased">   
        <NextauthProvider>
          {children}
        </NextauthProvider>
      </body>
    </html>
  );
}